stages:
  - build
  - test
  - deploy

variables:
 DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - apk update -qq
  - apk add --no-cache --virtual build-dependencies build-base ruby ruby-dev ruby-json
  - gem install bundler -v 1.16.1  --no-ri --no-rdoc
  - cd reddit
  - bundle install

build_job:
  stage: build
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

staging:
 stage: stage
 when: manual
 script:
  - echo 'Deploy'
 environment:
  name: stage
  url: https://beta.example.com
  
production:
 stage: production
 when: manual
 script:
  - echo 'Deploy'
 environment:
  name: production
  url: https://example.com



