image: ruby:2.4.2
variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
 DATABASE_URL: 'mongodb://mongo/user_posts'

build_job:
  image: docker:stable
  before_script:
    - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  services:
    - docker:dind
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375/
  script:
    - echo 'Building'
    - docker info
    - cd reddit
    - docker build --tag $CI_REGISTRY_IMAGE:reddit-app-$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:reddit-app-$CI_COMMIT_SHA

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - cd reddit
    - bundle install
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_job:
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
  stage: review
  script:
    - echo 'Deploy'
    - docker pull $CI_REGISTRY_IMAGE:reddit-app-$CI_COMMIT_SHA
    - docker run -d --name  $CI_REGISTRY_IMAGE:reddit-app-$CI_COMMIT_SHA -p 9292:9292 --rm
  environment:
    name: dev
    url: http://dev.example.com


branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
     - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
   
