gitlab_runner_registration_token: 'mNaDBDDi5BcD5NXjsrcQ'
gitlab_runner_coordinator_url: 'http://35.204.46.49'
gitlab_runner_docker_image: 'docker:latest'

gitlab_runner_runners:
  - name: 'Docker GitLab Runner'
    executor: docker
    docker_image: 'alpine'
    tags:
      - ruby
      - docker
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/cache"
    extra_configs:
      runners.docker:
        memory: 512m
        allowed_images: ["ruby:*", "python:*", "alpine:*"]
      runners.docker.sysctls:
        net.ipv4.ip_forward: "1"
