version: '3.3'
services:
  post_db:
    image: mongo:3.2
    env_file: .env
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
         - post_db
         - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    env_file: .env
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    env_file: .env
    networks:
      - back_net
      - front_net
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    env_file: .env
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  back_net:
    driver: ${NET_DRIVER}
    ipam:
      driver: default
      config:
        - subnet: ${NET_BACK}
  front_net:
    driver: ${NET_DRIVER}
    ipam:
      driver: default
      config:
        - subnet: ${NET_FRONT}
