plugin: gcp_compute
projects:
  - docker-249308
regions:
  - europe-west1
filters:
  - 'name = gitlabci-runners-*'
hostnames:
  - name
compose:
    ansible_host: networkInterfaces[0].accessConfigs[0].natIP
    internal_ip: networkInterfaces[0].networkIP
 
auth_kind: serviceaccount
service_account_file: ~/Projects/docker_credentials.json
