FROM python:3.6.0-alpine

COPY . /app
WORKDIR /app

RUN apk add --no-cache --update python3-dev  gcc build-base && \
    pip install -r /app/requirements.txt

ENV POST_DATABASE_HOST post_db
ENV POST_DATABASE posts

ENTRYPOINT ["python3", "post_app.py"]
